### ISSUE TITLE
Similar Project Question

### ISSUE THREAD

**Issue by rangersdesktop** [lhl/voicechat2#16]
I was working on something similar before I found your project. My latency from prompt end to response start is 1.5-2 sec:

https://github.com/rangersdesktop/TileProjectV1

I have a demo of an older version of the code and a writeup of the project on my website:
https://rangersdesk.top

I'm running a "Faster-whisper, Ooba API EXL2 model, and XTTS" stack with a 4080 and TR 1950X. You have a lot of experience with these parts so I was wondering if this was the best bet? What stack does VoiceChat2 use on Nvidia?

Thanks!

**Comment by lhl** [comment]
The `test` folder has a few different implementations that can be tried. If you want to leverage voicechat2's FE that reports latency, you can just swap components in and use that as a test harness. Good luck!
