### ISSUE TITLE
VAD Initialization Error

### ISSUE THREAD

**Issue by h3ck4** [lhl/voicechat2#17]
hi , im getting this error in the 0.0.0.0:8000 port , it says: "VAD Initialization Error"

this occur while im trying to record audio.already checked audio device in linux as input , works fine

also i've installed all dependencies and have an fresh python envrinment for this. 

![image](https://github.com/user-attachments/assets/4386d8a0-1f57-4127-959c-4fd43791da6f)

so can anyone help ?
its super frustrating

**Comment by h3ck4** [comment]
any help?, im so excited to use this, is there a good alternative you guys tested? , so i wouldn't download myself for test.

**Comment by lhl** [comment]
The browser based VAD uses https://github.com/ricky0123/vad - you could look there to see if anyone there has had similar problems, it's probably specific to your browser version. I'd recommend 1) taking a look at the error message in your browser console or 2) disabling the VAD completely and using the manual start/stop.
